### ISSUE TITLE
Problem with dependency

### ISSUE THREAD

**Issue by D063520** [marcocor/smaph-erd#3]
Hi, i was trying to run the service and apparently there is a problem with one of the dependencies. Can you give a look:

Could not resolve dependencies for project it.acubelab.smaph:smaph:jar:0.0.1-SNAPSHOT: Could not find artifact it.acubelab.batframework:bat-framework:jar:0.1 in dropbox (https://dl.dropboxusercontent.com/u/4663256/mvn-repository/)

Thank you
Dennis

**Comment by marcocor** [comment]
Hi Dennis,
the problem should have been solved with the last commit, where references to the BAT-Framework have been updated to point to the artifact on the Maven Central Repository.
Please note that this is old, unmaintained code referring to SMAPH-1. In the next two months I plan on removing it and replacing it with the new code that includes SMAPH-2 (see http://research.google.com/pubs/pub45537.html )

there is also a live demo of SMAPH-2 here: smaph.mkapp.it

**Comment by D063520** [comment]
Ciao marcocor (it's just a guess but I think you are italian ; ) ),

thank you for updating this repository! We want to test existing approaches for EL in the context of question answering. So yes we are also interested in further steps. Do you have a RESTFUL API for  SMAPH-2 that we can already access? 

Thank you
Dennis

**Comment by D063520** [comment]
Sorry again, 

apparently there is an issue with another dependency:

 Failed to execute goal on project smaph: Could not resolve dependencies for project it.acubelab.smaph:smaph:jar:0.0.1-SNAPSHOT: Could not find artifact it.cnr.isti.hpc:hpc-utils:jar:0.0.5 in central

Thank you
Dennis

**Comment by marcocor** [comment]
Whoops! I have updated the reference to hpc-utils and the nstructions: 
you are going to have to download hpc-utils and install it locally.

**Comment by marcocor** [comment]
Hi!
I am Italian indeed :)

There is a *very experimental* API that you can query through:
http://smaph.mkapp.it/rest/default-json?Text=armstrong%20moon%20landing

Please do not use it in production, it is unstable, intended for 
demonstration, and there is a global limit on monthly queries due to the 
limit set by the Bing API. Use it only for testing or building proofs of 
concept. In the next two months we are going to make the SMAPH service 
available in a more stable manner through D4Science.org.

Note that SMAPH is tuned to achieve maximum F1 in web queries, but 
currently does not return discarded annotations (that you might still 
find useful), and may work better if trained on a question answering 
corpus. I would say you can first have a try of smaph as-is, and later 
if you feel like something might need specific tuning we can work 
together on that. In that case, please contact me directly at 
cornolti@di.unipi.it.

Cheers
Marco

**Comment by D063520** [comment]
Thank you very much for your help!
